### PR TITLE
fix(FindUs): Water matches event's theme

### LINKED ISSUE #16: 🐛 Bug: Google Maps embeds aren't using event theme colors
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/halfstackconf-next/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

From the old site on https://halfstackconf.com/vienna/:

Screenshot of a Google Map embed with red colors

### Actual

On the new site, note the highlight colors are blue instead of red:

Screenshot of a Google Map embed with blue colors

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by retrohacker**
## PR Checklist

- [x] Addresses an existing open issue: fixes #16 
- [x] That issue was marked as [accepting prs](https://github.com/JoshuaKGoldberg/halfstackconf-next/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/halfstackconf-next/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

FindUs' Google Map embed's water color now matches the event's theme

Attempted getComputedStyles on a throw-away div created with document.createElement, but didn't have any luck and it broke SSR:

```
const div = document.CreateElement("div")
div.classList.add(styles[event])
document.getComputedStyles(div)
```

Instead, this PR pulls those variables into JS. Not sure if there is a better way to do this.

### CODE REVIEW

File: src/components/EventTheme/colors.tsx [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+    "color-primary-light": "#f3a7a9",
+  },
+  belgrade: {
+    "color-backdrop-subtle": "#e1ff99",
+    "color-faint": "#e1ff99",
+    "color-primary": "#7aa11c",
+    "color-primary-dark": "#304007",
+    "color-primary-light": "#e1ff99",
+  },
+} as Record<
```
Comment (JoshuaKGoldberg) [inline src/components/EventTheme/colors.tsx]: [Suggestion] Heh, the `as` type assertion is because keys of type `string` can't be used to index into this object, right? Until #18 is in I suppose there will always need to be some assertions. A fewer-lines-of-code solution would be to, instead of `as` asserting here, using an `as` in `EventColors`:

```ts
return colors[event as keyof typeof colors];
```

That way also has the added benefit of letting `colors` keep its more specific type. Which might be useful later on.


<details>
<summary>If we really wanted to, we could go through the effort of making it more safe...</summary>
I think TypeScript is right to yell here: what happens if someone makes a new event -say, `"philadelphia"`- and forgets to add to `colors.tsx`? The page will crash. I simulated this by deleting the `charlotte` entry and visiting `localhost:3000/charlotte` locally:

```plaintext
TypeError: Cannot read properties of undefined (reading 'color-backdrop-subtle')

src/pages/[event]/index.tsx (124:34) @ Event
  122 |     geolocation={geolocation}
  123 |     slug={slug}
> 124 |     waterColor={eventColors["color-backdrop-subtle"]}
      |                            ^
  125 |   />
  126 | )}
```

An alternative might be to instead change from `event: string` to a more specific type, like `event: EventName` or `event: EventSlug` or some name like that.

One way you could do that would be to:
1. Change `src/data/events.json` to `src/data/events.ts`
2. Have it `export const events = [...] as const` _(maybe even renaming it to `eventsOrder`, since that's what it's used for?)_
3. Also have `events.ts` `export const EventName = typeof events[number]`
4. Use that `EventName` type wherever something is meant to be an event

Note that this includes `getEvents()` in `src/data/index.ts`, which would need to `as EventSlug[]`... which I guess means there's always going to be be a type assertion until #18 is in.
</details>

File: src/components/EventTheme/index.tsx [hunk 2]
```diff
@@ -1,14 +1,23 @@
...
+
 export function EventTheme({ children, event }: EventThemeProps) {
   return (
     <div className={clsx(styles.eventTheme, styles[event])}>{children}</div>
   );
 }
+
+export function EventColors({ event }: EventColorProps) {
+  return colors[event];
+}
```
Comment (JoshuaKGoldberg) [inline src/components/EventTheme/index.tsx]: [Suggestion] This component and its prop type are named & structured like a React function component, but it's not actually used like one. It's used more like a _hook_. I think structuring it like one would be more idiomatic (and less code):

```suggestion
export function useEventColors(event: string) {
  return colors[event];
}
```

Thoughts?

File: src/pages/[event]/index.tsx [hunk 3]
```diff
@@ -36,6 +36,7 @@ export default function Event({
     year,
   },
 }: ReturnedProps<typeof getStaticProps>) {
+  const eventColors = EventColors({ event: slug });
```
Comment (JoshuaKGoldberg) [inline src/pages/[event]/index.tsx]: [Suggestion] I would move this into `FindUs`. The `waterColor` value isn't used until the `onLoad` callback inside that component, and the component also receives the `slug`. Fewer lines of code for the same result.

File: src/components/FindUs/createMapOptions.ts [hunk 4]
```diff
@@ -73,9 +77,7 @@ export const createMapOptions = () => ({
       featureType: "water",
       elementType: "all",
       stylers: [
-        {
-          color: "#072a74",
-        },
+        { color: waterColor },
```
Comment (JoshuaKGoldberg) [inline src/components/FindUs/createMapOptions.ts:80]: [Praise] Ah nice, glad it was this clean!

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Cool, nicely done getting this to work! It's been bugging me for a while 😄 

Left a couple of code suggestions. What do you think?

File: src/pages/[event]/index.tsx (hunk 3 above)
Comment (retrohacker) [reply src/pages/[event]/index.tsx]: Good call!

File: src/components/EventTheme/colors.tsx (hunk 1 above)
Comment (retrohacker) [reply src/components/EventTheme/colors.tsx]: Love this, going to give it a try. I think it'll end up being a bit bigger PR though.

Learned a lot of TS on this change so far. Didn't know you could do this with `as const`.

**Comment by retrohacker** [comment]
Thanks for the kind review and guidance, learned a lot about TS with this PR.

Let me know what you think!

File: src/data/types.ts [hunk 5]
```diff
@@ -80,10 +82,12 @@ export interface EventVideo {
...
+  otherEvents?: Record<EventName, number[]>;
   videos?: EventVideo[];
 }
 
 export interface EventDataJoined extends EventDataCurrent, EventDataDefault {
-  slug: string;
+  slug: EventName;
 }
+
+export type EventName = (typeof eventOrder)[number];
```
Comment (JoshuaKGoldberg) [inline src/data/types.ts]: [Suggestion] Looking through this PR, there are 15 `: EventName`s, 8 `event: EventNames`s, and 7 `slug: EventName`s. Maybe `EventSlug` would be more clear?

Not a blocker from me, just a thought 🙂

File: README.md [hunk 6]
```diff
@@ -114,7 +114,7 @@ pm2 start "pnpm production"
 
 Events are all stored in `src/data` as `.json` files.
 
-- [`src/data/events.json`](./src/data/events.json) contains the array of event lines that are listed on the homepage
+- [`src/data/events/index.ts`](./src/data/events/index.ts) contains the array of event lines that are listed on the homepage
```
Comment (JoshuaKGoldberg) [inline README.md:117]: [Praise] I probably would have forgotten to update these docs. Nice! 😄

File: src/components/EventTheme/colors.tsx [hunk 7]
```diff
@@ -0,0 +1,76 @@
+import { EventName } from "~/data/types";
+
+interface EventColors {
```
Comment (JoshuaKGoldberg) [inline src/components/EventTheme/colors.tsx]: [Suggestion] Since this interface is used in things available outside of this file (the type of `colors`), you might want to export it. It doesn't make a difference now but later on someone else might want to refer to it, and it can be confusing not having the interface available.

```suggestion
export interface EventColors {
```

(non-blocking, just a thought)

File: src/components/EventTheme/colors.tsx [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+  },
+  belgrade: {
+    "color-backdrop-subtle": "#e1ff99",
+    "color-faint": "#e1ff99",
+    "color-primary": "#7aa11c",
+    "color-primary-dark": "#304007",
+    "color-primary-light": "#e1ff99",
+  },
+};
+export default colors;
```
Comment (JoshuaKGoldberg) [inline src/components/EventTheme/colors.tsx]: [Style] I personally tend to avoid `export default`: https://basarat.gitbook.io/typescript/main-1/defaultisbad. Definitely not a blocker, but I'd suggest switching to `export const colors`.

File: src/components/FindUs/createMapOptions.ts [hunk 9]
```diff
@@ -1,4 +1,8 @@
-export const createMapOptions = () => ({
+interface createMapArguments {
```
Comment (JoshuaKGoldberg) [inline src/components/FindUs/createMapOptions.ts]: [Style] It's generally convention to PascalCase type names, not camelCase.

```suggestion
interface CreateMapArguments {
```

**Review by JoshuaKGoldberg — APPROVED** [review]
Awesome! Really thorough job hitting all the places. Even the docs! 👏 

Left a few suggestions/thoughts but nothing blocking. Yay!

**Comment by JoshuaKGoldberg** [comment]
By the way,

> ## PR Checklist
> * [ x ] Addresses an existing open issue: fixes #000
> * [ x ] That issue was marked as [accepting prs](https://github.com/JoshuaKGoldberg/halfstackconf-next/issues?q=is%3Aopen+is%3Aissue+label%3A%22accepting+prs%22+sort%3Aupdated-desc)
> * [ x ] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/halfstackconf-next/blob/main/.github/CONTRIBUTING.md?rgh-link-date=2023-09-12T18%3A59%3A12Z) were taken

f you switch the `[ x ]`s to `[x]` GitHub will render as a nice task list: https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/creating-a-tasklist

> fixes #000

`fixes #16`?

> Instead, this PR pulls those variables into JS. Not sure if there is a better way to do this.

Yeah 🤷 if the projects eventually moves to CSS-in-JS (#17) this'll all get resolved.
